conky.config = {
  background=false,
  out_to_console=true,
  out_to_x=false,
  update_interval=2,
  total_run_times=0,
  short_units=true,
  pad_percents=3,
};
conky.text = [[
,[{
    "full_text": " ❤ $acpitemp°C [$cpu%] ",
    "color": "\#F38BA8"
  },
  {
    "full_text": " ≣ ${memperc}% ",
    "color": "\#F9E2AF"
  },
  ${if_up wlp229s0}
    {
      "full_text": " ≈ ${execi 10 iw dev wlp229s0 link | sed -n '/SSID:/s/.*SSID: //p'} ",
      "color": "\#A6E3A1"
    },
  $endif
  {
    "full_text": " ϟ [$battery_percent%] ",
    "color": "\#CBA6F7"
  },
  {
    "full_text": " ♪ ${exec amixer -c 1 -M get Master | grep "Mono: Playback" | awk '{print $4}' | tr -d '[]'} ",
    "color": "\#89B4FA"
  },
  {
    "full_text": " ${time %a %b %d} ${time %H:%M} "
  }
]
]];
